### ISSUE TITLE
Problema em deploy de aplicação?

### ISSUE THREAD

**Issue by HakaCode** [LuanPetruitis/Proffy#1]
https://github.com/gustavoguanabara/git-github/issues/3#issuecomment-673755655

Olá @LuanPetruitis , tens problema em fazer o deploy da sua aplicação?

R: Tente ativar o Github Pages deve funcionar!

**Comment by LuanPetruitis** [comment]
Cara eu tento colocar no github pages mas não consigo
![image](https://user-images.githubusercontent.com/62400514/90197677-b0933080-dda5-11ea-9028-485fb208a37d.png)

**Comment by HakaCode** [comment]
@LuanPetruitis  ja leu a doc do github? talvez ja lhe ajude

**Comment by LuanPetruitis** [comment]
Vou dar uma lida

**Comment by HakaCode** [comment]
> Vou dar uma lida

Aproveitando tbm é uma boa pratica não subir a pasta `node_module` e por em um `.gitignore` ou simplesmente ignora quando der o commit 👍 (até onde sei 😆 )

**Comment by LuanPetruitis** [comment]
cara eu tirei o node_module ai instalo as dependencias ai quando dou um node server.js e acesso o localhost olha o erro que dá
![image](https://user-images.githubusercontent.com/62400514/90260304-b29ad500-de21-11ea-9819-cb7f648e2296.png)

**Comment by LuanPetruitis** [comment]
Cara eu publiquei o site, consegui mas olha como ficou mas mesmo publicando, na minha maquina fica com esse erro
https://luanpetruitis.github.io/Proffy/

**Comment by HakaCode** [comment]
> Cara eu publiquei o site, consegui mas olha como ficou mas mesmo publicando, na minha maquina fica com esse erro
> https://luanpetruitis.github.io/Proffy/

não pode escolher o change theme

**Comment by LuanPetruitis** [comment]
Man quando tu baixa o repositório tu consegue fazer o site funcionar

**Comment by HakaCode** [comment]
> Man quando tu baixa o repositório tu consegue fazer o site funcionar

Que estranho

**Comment by LuanPetruitis** [comment]
Man quando tu baixa o repositório tu consegue fazer o site funcionar??

**Comment by HakaCode** [comment]
> Man quando tu baixa o repositório tu consegue fazer o site funcionar??

Provavelmente sim

**Comment by LuanPetruitis** [comment]
Deve ser algum app no meu pc que esta impedindo então

**Comment by HakaCode** [comment]
> Deve ser algum app no meu pc que esta impedindo então

provavelmente, até agr não subi nenhuma aplicação desse porte, então não tenho muita experiencia

**Comment by LuanPetruitis** [comment]
Man mudou o tipo de erro

![image](https://user-images.githubusercontent.com/62400514/90298739-bc482b00-de69-11ea-8637-25b0e8e2f50c.png)

**Comment by HakaCode** [comment]
> Man mudou o tipo de erro
> 
> ![image](https://user-images.githubusercontent.com/62400514/90298739-bc482b00-de69-11ea-8637-25b0e8e2f50c.png)

pelo que entendi nesse meio tempo de github, tu sobe so os files mesmo, dps que tu baixa a aplicação tem que dar um `npm install` para que instale as dependencias e as paradas todas, teria que ter alguem mais experiente para te conduzir.

**Comment by LuanPetruitis** [comment]
Vlw cara muito obrigado pela colaboração

**Comment by HakaCode** [comment]
> Vlw cara muito obrigado pela colaboração

tranquilo man smp que precisar e estiver ao meu alcance so dar um toque 👍
